### ISSUE TITLE
Add option to have buttons change depending on state

### ISSUE THREAD

**Issue by Doa132** [iantrich/radial-menu#4]
It would be great if the centre button or the radial buttons could display a state of an entity. Such as changing colour or icon if the tv is on, or having the state written in text beneath. Sort of like combining it with the custom:button-card. 

<img width="274" alt="Screen Shot 2019-04-18 at 14 20 11" src="https://user-images.githubusercontent.com/43628930/56339399-7afe2780-61f1-11e9-84b2-21e0f049e9ea.png">
<img width="286" alt="Screen Shot 2019-04-18 at 14 17 46" src="https://user-images.githubusercontent.com/43628930/56339401-7e91ae80-61f1-11e9-9964-c2446cd67ad6.png">

**Comment by neomvll** [comment]
would be very nice !

**Comment by Villhellm** [comment]
I would also love to see this implemented. In my opinion pulling over the functionality of state_images from picture elements would make this custom card perfect

**Comment by tenkaibr** [comment]
I vote for this feature lol... It's the only thing left to be perfect

**Comment by iantrich** [comment]
So I think I'm going to be lazy on this and create a 2nd version of the card that actually uses the button-card to get super customization. I don't see a point in me trying to replicate all that functionality here.

**Comment by iantrich** [comment]
Anyone want to give this highly experimental version a try?
https://gist.github.com/iantrich/ebcbfdbec9a316618909840f06bcf057
```yaml
type: 'custom:radial-menu'
items:
  - entity: light.bed_light
    icon: 'mdi:flash'
    name: Bedroom Light
    tap_action:
      action: toggle
  - entity: alarm_control_panel.ha_alarm
    icon: 'mdi:alarm'
    name: Alarm Panel
    tap_action:
      action: more-info
  - entity: alarm_control_panel.ha_alarm
    icon: 'mdi:thermostat'
    name: Thermostat
  - config:
      type: 'custom:button-card'
      entity: light.bed_light
      show_name: false
      styles:
        card:
          - background-color: 'rgba(0, 0, 0, 0)'
          - box-shadow: 0px 0px 0px 0px black
```
